# Site settings
title: mfroach
# Site's name
name: mfroach's blog
author: mfroach
author_nickname: mfroach
email: mfro@pm.me
description: ""
baseurl: ""
url: "https://mfroach.github.io"
exclude: [vendor]
# TODO(max): Use pagefind (pagefind --source . --root-selector .container) but
# avoid scanning _site somehow.
include: [.well-known]

future: false

twitter:
  username: none

mastodon:
  username: none
  url: "https://mastodon.social/@none"

repo:
  repository_url: https://github.com/mfroach/mfroach.github.io
  branch: main

permalink: '/blog/:slug/'
post_dirs: false

# Build settings
markdown: kramdown
kramdown:
  input: GFM # GitHub Flavored Markdown
  hard_wrap: false
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - rouge

sass:
    style: compressed

collections:
    blog_lisp:
        output: true
        permalink: /blog/lisp/:path/
    recipes:
        output: true
        permalink: /recipes/:path/

default_og_image: "/favicon.ico"

rc_scout: "https://www.recurse.com/scout/click?t=e8845120d0b98bbc3341fa6fa69539bb"
citation_needed: "<sup>[<a href=\"https://en.wikipedia.org/wiki/Wikipedia:Citation_needed\"><i>citation needed</i></a>]</sup>"
